# Generated by Django 4.2.7 on 2023-11-10 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
            options={
                'ordering': ['title'],
                'indexes': [models.Index(fields=['title'], name='api_contact_title_2787e5_idx'), models.Index(fields=['slug'], name='api_contact_slug_80cefc_idx')],
            },
        ),
    ]
